//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodRequest
    {
        public FoodRequest()
        {
            this.FoodDistributes = new HashSet<FoodDistribute>();
        }
    
        public int Id { get; set; }
        public string FoodRequestId { get; set; }
        public Nullable<int> FoodSourceId { get; set; }
        public string FoodNames { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> NgoId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
    
        public virtual ICollection<FoodDistribute> FoodDistributes { get; set; }
        public virtual FoodSource FoodSource { get; set; }
        public virtual NGO NGO { get; set; }
    }
}
